apiVersion: v1
kind: Service
metadata:
  name: locust
  namespace: perf2
spec:
  clusterIP: None
  selector:
    app: locust-leader
  ports:
  - port: 8089
    targetPort: 8089
    name: http
  - port: 5557
    targetPort: 5557
    name:  tcp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-leader
  namespace: perf2
spec:
  selector:
    matchLabels:
      app: locust-leader
  template:
    metadata:
      labels:
        app: locust-leader
    spec:
      # affinity:
      #   nodeAffinity: # place pods only on the specified instance type
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node.kubernetes.io/instance-type
      #           operator: In
      #           values:
      #           - c6i.large
      containers:
      - name: locust-leader
        image: public.ecr.aws/docker/library/python:3.9.18-bookworm
        command: ["/bin/sh","-c"]
        args:
          - pip install locust && 
            git clone https://github.com/openobserve/benchmarker && 
            cd benchmarker && 
            pip install -r requirements.txt && 
            locust --master --web-auth admin:admin -f locustfile_ziox_multi_600.py
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8089
        - containerPort: 5557
